version: 2

services:
  - type: web
    name: tiendita-mejorada
    runtime: php
    plan: free
    buildCommand: echo "No build required for PHP"
    startCommand: php -S 0.0.0.0:$PORT server.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
