# Configuración para Render
# Este archivo define cómo se despliega la aplicación

# Comando de construcción
build:
  - composer install --no-dev --optimize-autoloader || echo "No composer.json found"
  - echo "Build completed"

# Comando de inicio
start: php -S 0.0.0.0:$PORT server.php

# Variables de entorno necesarias (configurar en Render Dashboard)
environment:
  - DB_HOST
  - DB_PORT
  - DB_NAME  
  - DB_USER
  - DB_PASSWORD
  - APP_ENV=production
  - APP_DEBUG=false

# Configuración del servicio
service:
  type: web
  runtime: php
  plan: free

# Archivos a ignorar en el despliegue
ignore:
  - .env
  - logs/
  - cache/
  - backups/
  - test-*.php
